
spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        # 告诉当前项目nacos-server所在的地址
        server-addr: 47.95.253.11:8848
        

server:
  # ip 就不用写了 192.168.56.1
  port: 8081
  
  