
# curl -X POST 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=order-service&ip=192.168.0.11&port=9091'



spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        # 告诉当前项目nacos-server所在的地址
        server-addr: 47.95.253.11:8848

server:
  # ip 就不用写了 192.168.56.1
  port: 9092